### ISSUE TITLE
Does wirespider installation assume wireguard is already installed?

### ISSUE THREAD

**Issue by bmullan** [SFTtech/wirespider#247]
Does wirespider install wireguard or does the user have to install wireguard before installing wirespider?

**Comment by returntoreality** [comment]
It does not install wireguard. Under linux it should work without the wireguard tools installed as long as the wireguard module is installed. But I would recommend installing the wireguard tools.

**Comment by bmullan** [comment]
Thanks, I assumed so but didn't see anything mentioned about it.
