### ISSUE TITLE
Error running 1st command in section "How to run the Server"

### ISSUE THREAD

**Issue by bmullan** [SFTtech/wirespider#85]
When I run the following command per the README.md

> /etc/wirespider$ **_sudo wirespider database migrate -d sqlite:/var/lib/wirespider/config.sqlite_**
> **error: Found argument '-d' which wasn't expected, or isn't valid in this context**
> 
> 	If you tried to supply `-d` as a value rather than a flag, use `-- -d`
> 
> USAGE:
>     wirespider database migrate

Is there an error in the documentation regarding the **_"-d"_** cmd option?

**Comment by returntoreality** [comment]
Interesting, indeed this is not working in the latest release (I think it might work with the DATABASE_URL environment variable). I tested the current main branch as well and there it works correctly though. If it helps I can do a release of the current main branch.

**Comment by bmullan** [comment]
@returntoreality 
thanks... I'm anxious to try wirespider out !
brian

**Comment by returntoreality** [comment]
I am currently rewriting large parts to make it more p2p and no longer require a single server instance. For the meantime I released 0.5.0, which fixes your issue.
