### ISSUE TITLE
Installation fails still 

### ISSUE THREAD

**Issue by bmullan** [SFTtech/wirespider#88]
Installation doc says to execute:

$ **wirespider database migrate -d sqlite:/var/lib/wirespider/config.sqlite**

_But executing that returns..._

> **thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', src/server/commands.rs:81:66**
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by returntoreality** [comment]
It should be fixed in the 0.5.1 release. I hope it works for you know. To be sure I tested the other server setup commands from the readme as well and they worked.
